// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW9GmBSKyD3O8hCzpnlbZrUvjMo4XIMjw',
    appId: '1:492295806420:web:61237eb93fefd655af0a41',
    messagingSenderId: '492295806420',
    projectId: 'token-system-ba96a',
    authDomain: 'token-system-ba96a.firebaseapp.com',
    storageBucket: 'token-system-ba96a.firebasestorage.app',
    measurementId: 'G-2WN7QPBLBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDq-6yRgcwflLlinu_Ij1oLMevmyppBM4',
    appId: '1:492295806420:android:d576b18b53636de0af0a41',
    messagingSenderId: '492295806420',
    projectId: 'token-system-ba96a',
    storageBucket: 'token-system-ba96a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs2MlHqBKgr_SXPqjIBG6CfT0_CexPYb8',
    appId: '1:492295806420:ios:296a8e49c3f71411af0a41',
    messagingSenderId: '492295806420',
    projectId: 'token-system-ba96a',
    storageBucket: 'token-system-ba96a.firebasestorage.app',
    iosBundleId: 'com.queuetoken.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs2MlHqBKgr_SXPqjIBG6CfT0_CexPYb8',
    appId: '1:492295806420:ios:296a8e49c3f71411af0a41',
    messagingSenderId: '492295806420',
    projectId: 'token-system-ba96a',
    storageBucket: 'token-system-ba96a.firebasestorage.app',
    iosBundleId: 'com.queuetoken.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW9GmBSKyD3O8hCzpnlbZrUvjMo4XIMjw',
    appId: '1:492295806420:web:954029e0e3b429f0af0a41',
    messagingSenderId: '492295806420',
    projectId: 'token-system-ba96a',
    authDomain: 'token-system-ba96a.firebaseapp.com',
    storageBucket: 'token-system-ba96a.firebasestorage.app',
    measurementId: 'G-6Z742L1D67',
  );
}
