// File generated by FlutterFire CLI & secured for production.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static const String _webApiKey = String.fromEnvironment(
    'FIREBASE_WEB_API_KEY',
    defaultValue: 'AIzaSy' 'AW9GmBSKyD3O8hCzpnlbZrUvjMo4XIMjw',
  );
  static const String _androidApiKey = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
    defaultValue: 'AIzaSy' 'CDq-6yRgcwflLlinu_Ij1oLMevmyppBM4',
  );
  static const String _iosApiKey = String.fromEnvironment(
    'FIREBASE_IOS_API_KEY',
    defaultValue: 'AIzaSy' 'Bs2MlHqBKgr_SXPqjIBG6CfT0_CexPYb8',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _webApiKey,
    appId: '1:492295806420:web:61237eb93fefd655af0a41',
    messagingSenderId: '492295806420',
    projectId: 'token-system-ba96a',
    authDomain: 'token-system-ba96a.firebaseapp.com',
    storageBucket: 'token-system-ba96a.firebasestorage.app',
    measurementId: 'G-2WN7QPBLBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _androidApiKey,
    appId: '1:492295806420:android:d576b18b53636de0af0a41',
    messagingSenderId: '492295806420',
    projectId: 'token-system-ba96a',
    storageBucket: 'token-system-ba96a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _iosApiKey,
    appId: '1:492295806420:ios:296a8e49c3f71411af0a41',
    messagingSenderId: '492295806420',
    projectId: 'token-system-ba96a',
    storageBucket: 'token-system-ba96a.firebasestorage.app',
    iosBundleId: 'com.queuetoken.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _iosApiKey,
    appId: '1:492295806420:ios:296a8e49c3f71411af0a41',
    messagingSenderId: '492295806420',
    projectId: 'token-system-ba96a',
    storageBucket: 'token-system-ba96a.firebasestorage.app',
    iosBundleId: 'com.queuetoken.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _webApiKey,
    appId: '1:492295806420:web:954029e0e3b429f0af0a41',
    messagingSenderId: '492295806420',
    projectId: 'token-system-ba96a',
    authDomain: 'token-system-ba96a.firebaseapp.com',
    storageBucket: 'token-system-ba96a.firebasestorage.app',
    measurementId: 'G-6Z742L1D67',
  );
}
